<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>balanceAfter</name>
   <tag></tag>
   <elementGuidId>5a421888-d1ba-4ac5-9f2a-96e28fc0b495</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div[2]/section/div[2]/div/table/tbody/tr/td[7]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;root&quot;)/div[1]/div[@class=&quot;page&quot;]/div[@class=&quot;sc-ifAKCX fAqSwo&quot;]/section[@class=&quot;sc-feJyhm aOQWm&quot;]/div[@class=&quot;sc-iAyFgw bwbobq&quot;]/div[@class=&quot;sc-kEYyzF cdTppb&quot;]/table[1]/tbody[1]/tr[1]/td[7][count(. | //td[@ref_element = 'Object Repository/dailyTesting/Frontend/statement/Page_UCF/iframe']) = count(//td[@ref_element = 'Object Repository/dailyTesting/Frontend/statement/Page_UCF/iframe'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>10,633.00</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[@class=&quot;page&quot;]/div[@class=&quot;sc-ifAKCX fAqSwo&quot;]/section[@class=&quot;sc-feJyhm aOQWm&quot;]/div[@class=&quot;sc-iAyFgw bwbobq&quot;]/div[@class=&quot;sc-kEYyzF cdTppb&quot;]/table[1]/tbody[1]/tr[1]/td[7]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/dailyTesting/Frontend/Betting/iframe</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <value>//div[@id='root']/div/div/div[2]/section/div[2]/div/table/tbody/tr/td[7]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bet'])[1]/following::td[3]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <value>//td[7]</value>
   </webElementXpaths>
</WebElementEntity>
