<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>1Arenawith100Match</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <lastRun>2018-10-22T16:30:29</lastRun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>ce670576-eb97-46b8-9e4a-367b726febb0</testSuiteGuid>
   <testCaseLink>
      <guid>b6e6a05a-bdf6-4530-93cf-05ae637b5d47</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Dev/Backoffice/Login/LoginAdmin</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>8f3fa816-7b62-421b-831a-460f89db4290</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Dev/Backoffice/Betting/Arena/Create_arena</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d7574496-cdb2-4292-bd02-5622ba15f44f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4566e842-e91b-4d11-a918-bcd13adb9b28</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b62a6192-0f0d-4a09-9648-211b871d4312</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bfaa5c52-54a0-482f-8ec5-582ab165ba27</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d539e95d-5750-4e10-a77c-4c96ba7311f7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bf1bcab7-4f17-4472-a940-e571178e41fb</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a384baaf-af1e-4b1d-86d4-02a7eb362877</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Dev/Backoffice/Betting/Matches/CreateMatch/Create match</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0080ab3b-b223-44db-aae9-e09929c677b5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9e4cc871-ad9d-40f3-a7f6-7efdbf81f650</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f1a27660-e3b4-4c3f-b598-c0e47c885574</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c4e56265-fba4-453e-a0a2-aaccb2bdae4b</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
