<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>ArenawithMatch</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <lastRun>2018-10-22T16:17:53</lastRun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>f7f72c27-48a2-4699-8097-577e136522b6</testSuiteGuid>
   <testCaseLink>
      <guid>ab4e2df0-ce1e-47ab-94ab-0e5abe5ef35a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Dev/Backoffice/Login/LoginAdmin</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>38ff6b76-d90a-43b0-ad85-c01bed770104</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Dev/Backoffice/Betting/Arena/Create_arena</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d7574496-cdb2-4292-bd02-5622ba15f44f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4566e842-e91b-4d11-a918-bcd13adb9b28</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b62a6192-0f0d-4a09-9648-211b871d4312</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bfaa5c52-54a0-482f-8ec5-582ab165ba27</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d539e95d-5750-4e10-a77c-4c96ba7311f7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bf1bcab7-4f17-4472-a940-e571178e41fb</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c1e3954d-1150-49f6-9297-ee211b74b4ba</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Dev/Backoffice/Betting/Matches/CreateMatch/Create match</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0080ab3b-b223-44db-aae9-e09929c677b5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9e4cc871-ad9d-40f3-a7f6-7efdbf81f650</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f1a27660-e3b4-4c3f-b598-c0e47c885574</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c4e56265-fba4-453e-a0a2-aaccb2bdae4b</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
