<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>ArenawithMatch3</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>c257c476-a06f-46f4-8171-d225b11e0ebd</testSuiteGuid>
   <testCaseLink>
      <guid>b6e6a05a-bdf6-4530-93cf-05ae637b5d47</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Staging/Backoffice/Login/LoginAdmin</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>8f3fa816-7b62-421b-831a-460f89db4290</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Staging/Backoffice/Betting/Create_arena</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7b7530a8-f503-48ce-b16a-bb35e8b5c22d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ce8c0e17-880b-4121-96e3-8e6f30aeff41</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>47e87d7c-1064-4bdf-8e0e-311ba2176bf2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>329c264d-ea39-46c8-8143-3d4f660c7227</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b7b38fe6-0436-45f1-bbe7-79aaa8262014</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f42ffc9f-a47e-4f83-8c05-96c6fd333a20</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a4fd7bfd-20ea-453c-b60e-1a7f6a9a017a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>05374cae-34c5-4f82-860a-5d9870f00de3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>89dc6611-a045-4f11-a3cf-4a7ed1346885</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a384baaf-af1e-4b1d-86d4-02a7eb362877</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Staging/Backoffice/Betting/Create_match</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c72b5dcd-4e55-4369-9917-0d459234b22c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6cc10297-0aff-4c44-8b37-3b159722bb25</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>758de455-6801-4ad6-9a6a-36e272102b59</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>196b6d2b-4e35-47f8-857b-5090d43b7ca0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4beb898a-5f15-431b-b775-75471f391fc4</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
