<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>oddsMeronWalaAutoTrigger</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>88c5d5a1-cffe-4374-8531-a601a9505c7b</testSuiteGuid>
   <testCaseLink>
      <guid>6a0d465a-5131-4b5e-a928-e3185b9aabb3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/dailyTesting/Backoffice/RiskManagement/oddsMeronWala</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>f29f1233-25c7-4a77-a53d-7d0770de1bf5</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/dailyTesting/riskManagement/autoTrigger</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>f29f1233-25c7-4a77-a53d-7d0770de1bf5</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>arenaName</value>
         <variableId>b83f7ef2-250b-4d25-ad68-bf6b9ead1ec9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>f29f1233-25c7-4a77-a53d-7d0770de1bf5</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>newOddsM</value>
         <variableId>762d3e92-181b-4bf4-b377-369e43af9345</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>f29f1233-25c7-4a77-a53d-7d0770de1bf5</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>newOddsW</value>
         <variableId>2bd4f598-9f54-4763-aab2-72d3c1dfb0d7</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
