<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>testing</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <lastRun>2018-11-13T18:23:48</lastRun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>e6d4c941-3993-4b35-a963-9e3c8c7c43e5</testSuiteGuid>
   <testCaseLink>
      <guid>d3730b3e-9228-4095-b9f8-5cc383cb668f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/dailyTesting/Backoffice/Login/backofficeLogin</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>48f23e9a-5611-4898-b03e-775ba46116db</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/dailyTesting/Backoffice/Match/createMatch</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>643ed803-069b-41ea-8534-c13fe41d3937</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>87bb6482-a1e9-4a36-b5b9-ad9d1c142b36</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>453b17dd-5888-4c72-b0d5-2b1b6e609790</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>83126a09-5ee0-472e-af7b-cda0c00e02ca</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7dacde0a-531c-4bbb-8d3f-4fe19904439d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a5c43c8b-3bf3-4295-92ab-f5b9980c9a93</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>afab1036-3b18-4e49-b688-0dc8454d7950</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8e96a773-edb5-416a-bdd1-5d8533075fe3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>def3ee02-5873-45cb-82d1-38a86427fe8f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7b8e3fc2-cbaa-4f2f-9095-a9d6451c2ac8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>30f2f368-9716-4eba-8316-c54172d8569c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5f0f5486-24d6-4f9e-8c0b-00f1f2634434</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
