<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Login</name>
   <tag></tag>
   <elementGuidId>ab6d72b5-8f2c-4115-934c-d6628675d88f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='submit']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;root&quot;)/div[1]/div[@class=&quot;page&quot;]/div[@class=&quot;styles__HeaderWrapper-sc-1cpcgf0-0 hUJbir&quot;]/div[@class=&quot;styles__ContainerWrapper-sc-1cpcgf0-1 kdkWci&quot;]/div[@class=&quot;styles__LoginWrapper-sc-1n50m2z-0 bIFgQd&quot;]/div[@class=&quot;right-sidebar-root&quot;]/div[@class=&quot;right-sidebar-content&quot;]/form[@class=&quot;sc-bxivhb gVGlWJ&quot;]/div[@class=&quot;sc-ifAKCX kfilsK position-relative form-group&quot;]/button[@class=&quot;sc-bZQynM dcIuaL btn btn-primary&quot;][count(. | //button[@type = 'submit' and (text() = 'Login' or . = 'Login')]) = count(//button[@type = 'submit' and (text() = 'Login' or . = 'Login')])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>false</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-bZQynM dcIuaL btn btn-primary</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Login</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[@class=&quot;page&quot;]/div[@class=&quot;styles__HeaderWrapper-sc-1cpcgf0-0 hUJbir&quot;]/div[@class=&quot;styles__ContainerWrapper-sc-1cpcgf0-1 kdkWci&quot;]/div[@class=&quot;styles__LoginWrapper-sc-1n50m2z-0 bIFgQd&quot;]/div[@class=&quot;right-sidebar-root&quot;]/div[@class=&quot;right-sidebar-content&quot;]/form[@class=&quot;sc-bxivhb gVGlWJ&quot;]/div[@class=&quot;sc-ifAKCX kfilsK position-relative form-group&quot;]/button[@class=&quot;sc-bZQynM dcIuaL btn btn-primary&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <value>//button[@type='submit']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <value>//div[@id='root']/div/div/div/div/div[2]/div/div/form/div/button</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign Up'])[1]/preceding::button[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Capture object:'])[1]/preceding::button[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <value>//button</value>
   </webElementXpaths>
</WebElementEntity>
